import {
  Home,
  About,
  ServicesHub,
  ServiceDetail,
  SolutionsHub,
  SolutionDetail,
  ProductsHub,
  ProductDetail,
  IndustriesHub,
  IndustryDetail,
  CaseStudiesHub,
  CaseStudyDetail,
  InsightsHub,
  BlogDetail,
  Faq,
  Team,
  Careers,
  JobDetail,
  Locations,
  Partners,
  Clients,
  Contact,
  GetQuote,
  ScheduleConsultation,
  ThankYou,
  PrivacyPolicy,
  Terms,
  CookiePolicy,
  NotFound,
} from "@/pages";

/** Eager route registry — keeps react-snap prerendering deterministic. */
export const routeElements = [
  { path: "/", element: <Home /> },
  { path: "/about", element: <About /> },
  { path: "/services", element: <ServicesHub /> },
  { path: "/services/:slug", element: <ServiceDetail /> },
  { path: "/solutions", element: <SolutionsHub /> },
  { path: "/solutions/:slug", element: <SolutionDetail /> },
  { path: "/products", element: <ProductsHub /> },
  { path: "/products/:slug", element: <ProductDetail /> },
  { path: "/industries", element: <IndustriesHub /> },
  { path: "/industries/:slug", element: <IndustryDetail /> },
  { path: "/case-studies", element: <CaseStudiesHub /> },
  { path: "/case-studies/:slug", element: <CaseStudyDetail /> },
  { path: "/insights", element: <InsightsHub /> },
  { path: "/insights/:slug", element: <BlogDetail /> },
  { path: "/faq", element: <Faq /> },
  { path: "/team", element: <Team /> },
  { path: "/careers", element: <Careers /> },
  { path: "/careers/:slug", element: <JobDetail /> },
  { path: "/locations", element: <Locations /> },
  { path: "/partners", element: <Partners /> },
  { path: "/clients", element: <Clients /> },
  { path: "/contact", element: <Contact /> },
  { path: "/get-a-quote", element: <GetQuote /> },
  { path: "/schedule-consultation", element: <ScheduleConsultation /> },
  { path: "/thank-you", element: <ThankYou /> },
  { path: "/privacy-policy", element: <PrivacyPolicy /> },
  { path: "/terms", element: <Terms /> },
  { path: "/cookie-policy", element: <CookiePolicy /> },
];

export { NotFound };